version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - DB_NAME=queryDB
      - MODEL_PATH=/app/models/gpt2
    depends_on:
      - mongodb
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - model_data:/app/models

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
  model_data: 